version: 2.1
jobs:
  build-lint-test:
    docker:
      - image: circleci/rust:stretch
    environment:
      RUST_BACKTRACE: "1"
      RUSTFLAGS: "-Dwarnings"
    working_directory: ~/port-inspector
    steps:
      - checkout:
          path: ~/port-inspector
      - run: cargo build
      - run: cargo fmt --all -- --check
      - run: cargo test


workflows:
  version: 2
  ci-test:
    jobs:
      - build-lint-test